name: TESTING
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json","README.md"]
baseurl: ""

collections:
  cats:
    output: true
    permalink: /cats/:path/

defaults:
    -
        scope:
            path:   ""
            type: "posts" #in Posts Folder using under values
        values:
            layout: "post"
